version: "3"

services:
  mongodb:
    image: mongo
    container_name: sae_tutorias_db
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # command: mongod --auth
    ports: 
      - "27019:27017"
    volumes:
      - volumen_data:/data/db
    networks:
      nodes-networks:
        aliases:
          - sae_tutorias_db

  sae_tutorias_ms:
    build:
      context: .
      dockerfile: Dockerfile.ms
    image: sae_tutorias_ms
    container_name: sae_tutorias_ms
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "127.0.0.6:3026:3026"
    networks:
      nodes-networks:
        aliases:
          - sae_tutorias_ms
  
  sae_serverTutorias_mq:
    build: 
      context: .
      dockerfile: Dockerfile.mq
    image: sae_serverTutorias_mq
    container_name: sae_serverTutorias_mq
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.10:5674:5672"
    networks:
      nodes-networks:
        aliases:
          - sae_serverTutorias_mq

volumes:
  volumen_data:

networks:
  nodes-networks:
    external: true