version: "2.15.1"

services:
  sae_tutorias_db:
    image: mongo:6.0.4
    ports: 
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: d1saebd
      MONGO_INITDB_ROOT_PASSWORD: papitas_0.*rt